### ISSUE TITLE
Merge with node-datahub-client?

### ISSUE THREAD

**Issue by mattpage** [flightstats/node-datahub#10]
There is a private repo [here](https://github.com/flightstats/node-datahub-client) which appears to have similar functionality. Perhaps a merger is possible? Seems like we should favor FOSS in this case.

**Comment by cmwood** [comment]
I believe the referenced private repo has methods supporting both hub v1 and hub v2. Since v1 is deprecated and going away completely, perhaps code that uses the private repo should utilize/augment this public module since the hub repo is also open to the public.

**Comment by mattpage** [comment]
@cmwood perhaps the v1 should say DEPRECATED and have a link pointing to this repo.

**Comment by cmwood** [comment]
Marked the 'old' private repo as deprecated. Closing this ticket.

**Comment by mattpage** [comment]
Excellent!
