### ISSUE TITLE
json:true not configurable for request-promise request

### ISSUE THREAD

**Issue by etburke** [flightstats/node-datahub#20]
We have a channel that returns csv data. Because we set json:true the hub returns a 406.

**Comment by cmwood** [comment]
I imagine there might be a similar need to POST/PUT, say CSV data, onto a channel?

**Comment by etburke** [comment]
I think that would require a breaking change. Can we hold off on that? This is tricky to test with nock, but we'll give it another shot.

**Comment by cmwood** [comment]
Cool, no worries. We can hold off.

**Comment by etburke** [comment]
Never mind on the test - this is completely, totally, 100% untestable.

**Comment by cmwood** [comment]
Hmm, I suppose if you wanted to try spending time to nock out a csv file using fast-csv or something you might be able to get a test written. Meh. I made a slight code suggestion. Otherwise, I'm fine with the change.

**Comment by cmwood** [comment]
Merged. And v2.0.1 published.
