### ISSUE TITLE
Just return a resolved or rejected promise

### ISSUE THREAD

**Issue by mattpage** [flightstats/node-datahub#5]
node-datahub currently handles promises. It catches errors generated by request-promise and returns status codes or it handles resolved promises. 

This is problematic. It means that errors have to be caught with "then" and that non-errors sometimes return data that does not reflect what the datahub api specifies.

**Comment by mattpage** [comment]
Hey @cmwood, is this on your radar? We could tag team this if you like.

**Comment by cmwood** [comment]
@mattpage Indeed, working on simply returning promise'd results. No more handling the promises in the library. Should have something ready by Monday.

**Comment by mattpage** [comment]
This is now fixed.
